project:
  type: website
  output-dir: docs

website:
  title: "PJ's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/trainorpj
      - icon: linkedin
        href: https://www.linkedin.com/in/trainorpj/

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    code-fold: true



